name: myfirst-action
on: workflow_dispatch
jobs:
  myfirstjob:
    runs-on: ubuntu-latest
    environment: Test
    steps:
    - name: Print "Greetings"
      run: echo "Hello there"
    - name: Print "Cogratulations"
      run: echo "From, ${{ vars.MY_NAME}}"
  surname:
    needs: myfirstjob
    runs-on: ubuntu-latest
    steps:
    - name: Surname
      run: echo "Surname - ${{ secrets.MY_SURNAME }}"
    
