name: myfirst-action
on: workflow_dispatch
jobs:
  myfirstjob:
    runs-on: ubuntu-latest
    steps:
    - name: Print "Greetings"
      run: echo "Hello there"
    - name: Print "Cogratulations"
      run: echo "From Manjitha"
